name: build-and-test

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: gcc

      - name: build exe
        run: gcc main.c dynamic_array.c linked_list.c hash_table.c -o memoryexplorer.exe

      - name: test exe
        run: .\memoryexplorer.exe

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: memoryexplorer-windows
          path: |
            memoryexplorer.exe
            data.txt

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: build exe
        run: gcc main.c dynamic_array.c linked_list.c hash_table.c -o memoryexplorer

      - name: test exe
        run: ./memoryexplorer

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: memoryexplorer-mac
          path: |
            memoryexplorer
            data.txt
